[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

[fork]
url = "${MAINNET_RPC_URL}"
block_number = 19000000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
